apiVersion: v1
kind: ConfigMap
metadata:
  name: go-api-config
  namespace: default
  labels:
    app.kubernetes.io/name: go-api-service
    app.kubernetes.io/part-of: go-90-days-challenge
data:
  PORT: "8080"
  APP_ENV: "production"
  LOG_LEVEL: "info"
  APP_VERSION: "1.0.0"
