apiVersion: v1
kind: Secret
metadata:
  name: go-api-secret
  namespace: default
  labels:
    app.kubernetes.io/name: go-api-service
type: Opaque
stringData:
  API_KEY: "k8s-prod-secret-token-9988"
  DB_PASSWORD: "supersecretpassword123"
